# Generated by Django 4.2.6 on 2023-11-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_tbl_videos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_videos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
